import 'server-only';

import { timingSafeEqual } from 'node:crypto';
import { getAdminSupabase } from '@/lib/supabase/admin';

/**
 * Server-only helpers for the gated full résumé download (ADR 0007).
 *
 * The contact-bearing PDF is generated by `scripts/generate-resume-pdf.ts` and
 * stored in a PRIVATE Supabase Storage bucket (never `public/`). Delivery is a
 * short-lived signed URL minted here, used by the Phase 2 approval email.
 */

/** Private Supabase Storage bucket holding the contact-bearing résumé PDF. */
export const RESUME_BUCKET = 'resume-private';

/** Stable object key for the current full résumé PDF (overwritten on regen). */
export const RESUME_OBJECT_KEY = 'resume-full.pdf';

/** Signed-URL lifetime: 72 hours (ADR 0007, OQ-4). */
export const RESUME_SIGNED_URL_TTL_SECONDS = 72 * 60 * 60;

/** Constant-time string comparison that also guards against length leaks. */
function safeEqual(a: string, b: string): boolean {
    const ab = Buffer.from(a);
    const bb = Buffer.from(b);
    if (ab.length !== bb.length) return false;
    return timingSafeEqual(ab, bb);
}

/**
 * True when `token` matches the configured `RESUME_FULL_TOKEN`. Returns false
 * when the env var is unset (feature not configured) or the token is absent —
 * so the `/resume/full` route falls back to the admin-session check rather than
 * granting access. Constant-time to avoid a timing oracle on the secret.
 */
export function isValidResumeFullToken(
    token: string | null | undefined,
): boolean {
    const expected = process.env.RESUME_FULL_TOKEN?.trim();
    if (!expected || !token) return false;
    return safeEqual(token, expected);
}

export type ResumeDownloadUrlResult =
    | { ok: true; url: string; expiresInSeconds: number }
    | {
          ok: false;
          reason: 'unconfigured' | 'not_found' | 'error';
          detail?: string;
      };

/**
 * Mint a short-lived signed URL for the private résumé PDF. Returns a
 * discriminated result rather than throwing:
 *  - `unconfigured` — the service-role client isn't available (missing env).
 *  - `not_found` — the object hasn't been generated/uploaded yet.
 *  - `error` — any other storage failure (detail included).
 */
export async function getResumeDownloadSignedUrl(): Promise<ResumeDownloadUrlResult> {
    const admin = getAdminSupabase();
    if (!admin.ok) return { ok: false, reason: 'unconfigured' };

    const { data, error } = await admin.client.storage
        .from(RESUME_BUCKET)
        .createSignedUrl(RESUME_OBJECT_KEY, RESUME_SIGNED_URL_TTL_SECONDS);

    if (error || !data) {
        const detail = error?.message ?? 'unknown error';
        const missing = /not.?found/i.test(detail);
        return { ok: false, reason: missing ? 'not_found' : 'error', detail };
    }

    return {
        ok: true,
        url: data.signedUrl,
        expiresInSeconds: RESUME_SIGNED_URL_TTL_SECONDS,
    };
}
