/* eslint-disable @typescript-eslint/no-require-imports, no-console */
const fs = require('fs')
const path = require('path')

function main() {
    try {
        const idxPath = path.join(__dirname, '..', '.contentlayer', 'generated', 'Post', '_index.json')
        if (!fs.existsSync(idxPath)) {
            console.error('No generated content index found — failing content check')
            process.exit(1)
        }
        const raw = fs.readFileSync(idxPath, 'utf8')
        const data = JSON.parse(raw)
        if (!Array.isArray(data) || data.length === 0) {
            console.error('No content generated by Contentlayer — failing content check')
            process.exit(1)
        }
        console.log(`Content check passed: ${data.length} posts`)
    } catch (err) {
        console.error('Content check failed:', err)
        process.exit(1)
    }
}

module.exports = { main }

if (require.main === module) {
    main()
}