import { pathToFileURL } from 'url'

async function main() {
  try {
    const mod = await import(pathToFileURL('./.contentlayer/generated/index.mjs').href)
    if (!mod.allPosts || mod.allPosts.length === 0) {
      console.error('No content generated by Contentlayer — failing content check')
      process.exit(1)
    }
    console.log(`Content check passed: ${mod.allPosts.length} posts`)
  } catch (err) {
    console.error('Content check failed:', err)
    process.exit(1)
  }
}

main()