import fs from 'fs';
import path from 'path';

export function main(): void {
    try {
        const postIdx = path.join(process.cwd(), '.contentlayer', 'generated', 'Post', '_index.json');
        const philIdx = path.join(process.cwd(), '.contentlayer', 'generated', 'Philosophy', '_index.json');

        const hasPost = fs.existsSync(postIdx);
        const hasPhil = fs.existsSync(philIdx);

        if (!hasPost && !hasPhil) {
            console.error('No generated content indices found — failing content check');
            process.exit(1);
        }

        let total = 0;
        if (hasPost) {
            const raw = fs.readFileSync(postIdx, 'utf8');
            const data = JSON.parse(raw);
            if (Array.isArray(data)) total += data.length;
        }
        if (hasPhil) {
            const raw = fs.readFileSync(philIdx, 'utf8');
            const data = JSON.parse(raw);
            if (Array.isArray(data)) total += data.length;
        }

        if (total === 0) {
            console.error('No content generated by Contentlayer — failing content check');
            process.exit(1);
        }
        console.log(`Content check passed: ${total} documents (Post + Philosophy)`);
    } catch (err) {
        console.error('Content check failed:', err);
        process.exit(1);
    }
}

// When executed directly (CLI), run main(). Tests import this module and call `main()` themselves.
if (process.argv[1] && (process.argv[1].endsWith('check-content.ts') || process.argv[1].endsWith('check-content.js'))) {
    main();
}
