import fs from 'fs'
import path from 'path'

export function main(): void {
    try {
        const idxPath = path.join(process.cwd(), '.contentlayer', 'generated', 'Post', '_index.json')
        if (!fs.existsSync(idxPath)) {
            console.error('No generated content index found — failing content check')
            process.exit(1)
        }
        const raw = fs.readFileSync(idxPath, 'utf8')
        const data = JSON.parse(raw)
        if (!Array.isArray(data) || data.length === 0) {
            console.error('No content generated by Contentlayer — failing content check')
            process.exit(1)
        }
        console.log(`Content check passed: ${data.length} posts`)
    } catch (err) {
        console.error('Content check failed:', err)
        process.exit(1)
    }
}

// When executed directly (CLI), run main(). Tests import this module and call `main()` themselves.
if (process.argv[1] && (process.argv[1].endsWith('check-content.ts') || process.argv[1].endsWith('check-content.js'))) {
    main()
}
